In [1]:
import numpy as np

# ===========================================
# Autoregressive Causal Language Model
# (After BPE Tokenizer)
# ===========================================

np.set_printoptions(precision=3, suppress=True)

# -------------------------------------------
# Step 1 : Token IDs (Output from BPE)
# -------------------------------------------

token_ids = np.array([2, 5, 8, 4])

vocab_size = 10
embedding_dim = 6
sequence_length = len(token_ids)

print("Token IDs:")
print(token_ids)

# -------------------------------------------
# Step 2 : Token Embedding
# -------------------------------------------

np.random.seed(42)

embedding_matrix = np.random.randn(vocab_size, embedding_dim)

embeddings = embedding_matrix[token_ids]

print("\nToken Embeddings:")
print(embeddings)

# -------------------------------------------
# Step 3 : Positional Encoding
# -------------------------------------------

def positional_encoding(seq_len, d_model):

    PE = np.zeros((seq_len, d_model))

    for pos in range(seq_len):

        for i in range(0, d_model, 2):

            angle = pos / (10000 ** (i / d_model))

            PE[pos, i] = np.sin(angle)

            if i + 1 < d_model:
                PE[pos, i + 1] = np.cos(angle)

    return PE


PE = positional_encoding(sequence_length, embedding_dim)

X = embeddings + PE

print("\nEmbeddings + Positional Encoding:")
print(X)

# -------------------------------------------
# Step 4 : Query, Key, Value
# -------------------------------------------

Wq = np.random.randn(embedding_dim, embedding_dim)
Wk = np.random.randn(embedding_dim, embedding_dim)
Wv = np.random.randn(embedding_dim, embedding_dim)

Q = X @ Wq
K = X @ Wk
V = X @ Wv

# -------------------------------------------
# Step 5 : Scaled Dot Product Attention
# -------------------------------------------

scores = (Q @ K.T) / np.sqrt(embedding_dim)

# -------------------------------------------
# Step 6 : Causal Mask
# -------------------------------------------

mask = np.triu(np.ones((sequence_length, sequence_length)), k=1)

scores = np.where(mask == 1, -1e9, scores)

print("\nMasked Attention Scores:")
print(scores)

# -------------------------------------------
# Step 7 : Softmax Function
# -------------------------------------------

def softmax(x):

    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))

    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)


attention_weights = softmax(scores)

print("\nAttention Weights:")
print(attention_weights)

# -------------------------------------------
# Step 8 : Context Vector
# -------------------------------------------

context_vector = attention_weights @ V

print("\nContext Vector:")
print(context_vector)

# -------------------------------------------
# Step 9 : Output Linear Layer
# -------------------------------------------

Wo = np.random.randn(embedding_dim, vocab_size)

logits = context_vector @ Wo

print("\nLogits:")
print(logits)

# -------------------------------------------
# Step 10 : Prediction
# -------------------------------------------

probabilities = softmax(logits)

print("\nPrediction Probabilities:")
print(probabilities)

# -------------------------------------------
# Step 11 : Next Token Prediction
# -------------------------------------------

predicted_tokens = np.argmax(probabilities, axis=1)

print("\nPredicted Next Token IDs:")
print(predicted_tokens)

# -------------------------------------------
# Step 12 : Summary
# -------------------------------------------

print("\n==============================")
print("MODEL EXECUTED SUCCESSFULLY")
print("==============================")

print("Sequence Length :", sequence_length)
print("Vocabulary Size :", vocab_size)
print("Embedding Size  :", embedding_dim)

Token IDs:
[2 5 8 4]

Token Embeddings:
[[ 0.242 -1.913 -1.725 -0.562 -1.013  0.314]
 [-0.602  1.852 -0.013 -1.058  0.823 -1.221]
 [ 0.344 -1.763  0.324 -0.385 -0.677  0.612]
 [-0.544  0.111 -1.151  0.376 -0.601 -0.292]]

Embeddings + Positional Encoding:
[[ 0.242 -0.913 -1.725  0.438 -1.013  1.314]
 [ 0.24   2.393  0.033 -0.059  0.825 -0.221]
 [ 1.253 -2.179  0.417  0.611 -0.673  1.612]
 [-0.403 -0.879 -1.012  1.366 -0.594  0.708]]

Masked Attention Scores:
[[ 7.177e+00 -1.000e+09 -1.000e+09 -1.000e+09]
 [-1.019e+01  3.888e+00 -1.000e+09 -1.000e+09]
 [ 5.461e+00 -2.719e+00  4.438e-01 -1.000e+09]
 [ 5.356e+00  4.135e+00 -7.760e+00  1.396e+00]]

Attention Weights:
[[1.    0.    0.    0.   ]
 [0.    1.    0.    0.   ]
 [0.993 0.    0.007 0.   ]
 [0.761 0.224 0.    0.015]]

Context Vector:
[[-1.706 -1.517  3.878  1.438  2.574  0.624]
 [ 2.968 -2.254 -0.872  3.892 -5.019  0.647]
 [-1.708 -1.493  3.85   1.422  2.587  0.629]
 [-0.639 -1.664  2.783  1.965  0.873  0.614]]

Logits:
[[ -1.358  -